### ISSUE TITLE
Patient Appointment Tab Layout Issue

### ISSUE THREAD

**Issue by razstvien01** [SinadjanRudge/doct#8]
- Modify the Patient Tab Layout just like the Record Patient Tab Layout.
- Only the PatientHome and the fragments folder are in the patient folder, not included move it in the fragments folder and rename it.
- Duplicate codes.
- Duplicate layouts in the .xml files

**Comment by RevyaS** [comment]
PR had been approved, other bugs will be assigned to another Issue. Closing this issue.
